export const VIPASSANA_CENTERS = [
    {
        "s_no": "1.0",
        "center_name": "Nepal Vipassana Center",
        "center_dhamma_name": "Dharmashringa",
        "address": "Budhanilkantha Municipality,\nWard no. 1, \nMuhanpokhari, Budhanilkantha, \nKathmandu(District)",
        "established_date": "1981",
        "contact_person": "Sushil Sah\n9813282200",
        "dhamma_hall_capacity_male": "120.0",
        "dhamma_hall_capacity_female": "120.0",
        "residence_capacity_male": "170.0",
        "residence_capacity_female": "100.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "Yes",
        "remarks": "",
        "extracted_city": "Kathmandu",
        "geocoding_address": "Kathmandu, Nepal",
        "latitude": "27.708317",
        "longitude": "85.3205817",
        "center_url": "https://www.dhamma.org/en/schedules/schshringa"
    },
    {
        "s_no": "2.0",
        "center_name": "Kotdada Vipassana Center",
        "center_dhamma_name": "Dhammagara",
        "address": "Godawari-2, Kotdada\nLalitpur",
        "established_date": "2018",
        "contact_person": "Kiran Maharjan\n9841482398",
        "dhamma_hall_capacity_male": "50.0",
        "dhamma_hall_capacity_female": "50.0",
        "residence_capacity_male": "22.0",
        "residence_capacity_female": "18.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "No",
        "remarks": "",
        "extracted_city": "Lalitpur",
        "geocoding_address": "Lalitpur, Nepal",
        "latitude": "27.6765635",
        "longitude": "85.3166069",
        "center": "https://www.dhamma.org/en/schedules/schagara"
    },
    {
        "s_no": "3.0",
        "center_name": "Kirtipur Vipassana Center",
        "center_dhamma_name": "DhammaKitti",
        "address": "Kirtipur Municipality\nDevkota-2, Kirtipur",
        "established_date": "2005/2006",
        "contact_person": "9841337418",
        "dhamma_hall_capacity_male": "20.0",
        "dhamma_hall_capacity_female": "20.0",
        "residence_capacity_male": "30.0",
        "residence_capacity_female": "30.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "No",
        "remarks": "",
        "extracted_city": "Kirtipur",
        "geocoding_address": "Kirtipur, Nepal",
        "latitude": "27.676664",
        "longitude": "85.2782438",
        "center": "https://www.dhamma.org/en/schedules/schkitti"
    },
    {
        "s_no": "4.0",
        "center_name": "Kakani Vipassana Center",
        "center_dhamma_name": "Dhamma Nibha",
        "address": "Kakani Rural Municipality-2\nNuwakot",
        "established_date": "",
        "contact_person": "",
        "dhamma_hall_capacity_male": "",
        "dhamma_hall_capacity_female": "",
        "residence_capacity_male": "",
        "residence_capacity_female": "",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "",
        "remarks": "Under Construction",
        "extracted_city": "Nuwakot",
        "geocoding_address": "Nuwakot, Nepal",
        "latitude": "27.9257991",
        "longitude": "85.248672",
        "center": "https://www.dhamma.org/en/schedules/schnibha"
    },
    {
        "s_no": "5.0",
        "center_name": "Nakkhu Prison Vipassana Center",
        "center_dhamma_name": "Dhammasaya",
        "address": "",
        "established_date": "2024",
        "contact_person": "Sushil Sah\n9813282200",
        "dhamma_hall_capacity_male": "80.0",
        "dhamma_hall_capacity_female": "",
        "residence_capacity_male": "42.0",
        "residence_capacity_female": "",
        "at_residence_male": "Y",
        "at_residence_female": "",
        "pagoda": "No",
        "remarks": "Only for Prisoners\nOne Gender at a time",
        "extracted_city": "",
        "geocoding_address": "Nakkhu Prison Vipassana Center, Nepal",
        "latitude": "27.6648",
        "longitude": "85.324",
        "center": "https://www.dhamma.org/en/schedules/schsushil"
    },
    {
        "s_no": "6.0",
        "center_name": "Lumbini Vipassana Center",
        "center_dhamma_name": "Dhamma Janani",
        "address": "Lumbini",
        "established_date": "2057 BS/2001AD",
        "contact_person": "",
        "dhamma_hall_capacity_male": "75.0",
        "dhamma_hall_capacity_female": "75.0",
        "residence_capacity_male": "24.0",
        "residence_capacity_female": "24.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "Yes(85)",
        "remarks": "",
        "extracted_city": "Lumbini",
        "geocoding_address": "Lumbini, Nepal",
        "latitude": "28.0654626",
        "longitude": "82.535642",
        "center": "https://www.dhamma.org/en/schedules/schjanani"
    },
    {
        "s_no": "7.0",
        "center_name": "Debdaha Vipassana Center",
        "center_dhamma_name": "",
        "address": "Debdaha Municipality-8\nLumbini",
        "established_date": "2023",
        "contact_person": "",
        "dhamma_hall_capacity_male": "",
        "dhamma_hall_capacity_female": "",
        "residence_capacity_male": "",
        "residence_capacity_female": "",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "",
        "remarks": "Under Construction",
        "extracted_city": "Lumbini",
        "geocoding_address": "Lumbini, Nepal",
        "latitude": "28.0654626",
        "longitude": "82.535642",
        "center": "https://www.dhamma.org/en/schedules/schdebdaha"
    },
    {
        "s_no": "8.0",
        "center_name": "Kapilvastu Vipassana Center",
        "center_dhamma_name": "Dhamma Nanadana",
        "address": "Banganga\nMadhuwandham\nKapilbastu",
        "established_date": "2020",
        "contact_person": "",
        "dhamma_hall_capacity_male": "25.0",
        "dhamma_hall_capacity_female": "25.0",
        "residence_capacity_male": "18.0",
        "residence_capacity_female": "12.0",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "No",
        "remarks": "",
        "extracted_city": "",
        "geocoding_address": "Kapilvastu Vipassana Center, Nepal",
        "latitude": "27.5517986",
        "longitude": "83.0468775",
        "center": "https://www.dhamma.org/en/schedules/schnanadana"
    },
    {
        "s_no": "9.0",
        "center_name": "Palpa Vipassana Center",
        "center_dhamma_name": "Dhamma Sisa",
        "address": "Madan Pokhara, 8,\nTansen,",
        "established_date": "",
        "contact_person": "",
        "dhamma_hall_capacity_male": "25.0",
        "dhamma_hall_capacity_female": "25.0",
        "residence_capacity_male": "18.0",
        "residence_capacity_female": "22.0",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "No",
        "remarks": "",
        "extracted_city": "Pokhara",
        "geocoding_address": "Pokhara, Nepal",
        "latitude": "28.209538",
        "longitude": "83.991402",
        "center": "https://www.dhamma.org/en/schedules/chissisa"
    },
    {
        "s_no": "10.0",
        "center_name": "Pokhara Vipassana Center",
        "center_dhamma_name": "Dhamma Pokhara",
        "address": "Pokhara -31, Kashki",
        "established_date": "2007",
        "contact_person": "",
        "dhamma_hall_capacity_male": "25.0",
        "dhamma_hall_capacity_female": "25.0",
        "residence_capacity_male": "16.0",
        "residence_capacity_female": "16.0",
        "at_residence_male": "Y",
        "at_residence_female": "N",
        "pagoda": "No",
        "remarks": "",
        "extracted_city": "Pokhara",
        "geocoding_address": "Pokhara, Nepal",
        "latitude": "28.209538",
        "longitude": "83.991402",
        "center": "https://www.dhamma.org/en/schedules/schpokhara"
    },
    {
        "s_no": "11.0",
        "center_name": "Chitwan Vipassana Center",
        "center_dhamma_name": "Dhamma Chitwan",
        "address": "Bharatpur Metromunicipality-16,\nChitwan",
        "established_date": "",
        "contact_person": "",
        "dhamma_hall_capacity_male": "35.0",
        "dhamma_hall_capacity_female": "35.0",
        "residence_capacity_male": "19.0",
        "residence_capacity_female": "15.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "36",
        "remarks": "",
        "extracted_city": "Chitwan",
        "geocoding_address": "Chitwan, Nepal",
        "latitude": "27.618086",
        "longitude": "84.4536201",
        "center": "https://www.dhamma.org/en/schedules/schchitwan"
    },
    {
        "s_no": "12.0",
        "center_name": "Dhamma Tarai Vipassan Center",
        "center_dhamma_name": "Dhamma Tarai",
        "address": "Parwanipur \nBirgunj",
        "established_date": "1997",
        "contact_person": "",
        "dhamma_hall_capacity_male": "30.0",
        "dhamma_hall_capacity_female": "30.0",
        "residence_capacity_male": "20.0",
        "residence_capacity_female": "12.0",
        "at_residence_male": "Y",
        "at_residence_female": "",
        "pagoda": "Yes",
        "remarks": "",
        "extracted_city": "Birgunj",
        "geocoding_address": "Birgunj, Nepal",
        "latitude": "27.0135196",
        "longitude": "84.8763804",
        "center": "https://www.dhamma.org/en/schedules/schbirat"
    },
    {
        "s_no": "13.0",
        "center_name": "Purbanchal Vipassana Center",
        "center_dhamma_name": "Dhamma Birat",
        "address": "Itahari-8, Sunsari",
        "established_date": "2000",
        "contact_person": "",
        "dhamma_hall_capacity_male": "30.0",
        "dhamma_hall_capacity_female": "30.0",
        "residence_capacity_male": "30.0",
        "residence_capacity_female": "30.0",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "Under Construction",
        "remarks": "",
        "extracted_city": "Itahari",
        "geocoding_address": "Itahari, Nepal",
        "latitude": "26.6622505",
        "longitude": "87.2748964",
        "center": "https://www.dhamma.org/en/schedules/schsuriyo"
    },
    {
        "s_no": "14.0",
        "center_name": "Ilam Vipassana Center",
        "center_dhamma_name": "Dhamma Suriyo",
        "address": "Gairigaun, Phikkal, Illam",
        "established_date": "2017",
        "contact_person": "",
        "dhamma_hall_capacity_male": "15.0",
        "dhamma_hall_capacity_female": "15.0",
        "residence_capacity_male": "10.0",
        "residence_capacity_female": "10.0",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "",
        "remarks": "",
        "extracted_city": "",
        "geocoding_address": "Ilam Vipassana Center, Nepal",
        "latitude": "26.9023331",
        "longitude": "88.0838159",
        "center": "https://www.dhamma.org/en/schedules/schsuriyo"
    },
    {
        "s_no": "15.0",
        "center_name": "Surkhetta Vipassana Center",
        "center_dhamma_name": "Dhamma Surkhetta",
        "address": "Katkuwa-8\nbirendranagar\nSurkhet",
        "established_date": "2012",
        "contact_person": "",
        "dhamma_hall_capacity_male": "25.0",
        "dhamma_hall_capacity_female": "25.0",
        "residence_capacity_male": "28.0",
        "residence_capacity_female": "15.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "",
        "remarks": "",
        "extracted_city": "Surkhet",
        "geocoding_address": "Surkhet, Nepal",
        "latitude": "28.6573817",
        "longitude": "81.5137825",
        "center": "https://www.dhamma.org/en/schedules/schsurkhetta"
    },
    {
        "s_no": "16.0",
        "center_name": "Dang Vipassana Center",
        "center_dhamma_name": "Dhamma Parag",
        "address": "Ghorahi-13,\nDang",
        "established_date": "",
        "contact_person": "",
        "dhamma_hall_capacity_male": "25.0",
        "dhamma_hall_capacity_female": "25.0",
        "residence_capacity_male": "18.0",
        "residence_capacity_female": "12.0",
        "at_residence_male": "",
        "at_residence_female": "",
        "pagoda": "",
        "remarks": "",
        "extracted_city": "Dang",
        "geocoding_address": "Dang, Nepal",
        "latitude": "27.9788799",
        "longitude": "82.4684176",
        "center": "https://www.dhamma.org/en/schedules/schparag"
    },
    {
        "s_no": "17.0",
        "center_name": "Sudur Paschim Vipassana Center",
        "center_dhamma_name": "Dhamma Yana",
        "address": "Tilachaur-8, \nMahendranagar",
        "established_date": "2023",
        "contact_person": "",
        "dhamma_hall_capacity_male": "36.0",
        "dhamma_hall_capacity_female": "36.0",
        "residence_capacity_male": "26.0",
        "residence_capacity_female": "24.0",
        "at_residence_male": "Y",
        "at_residence_female": "Y",
        "pagoda": "NO",
        "remarks": "",
        "extracted_city": "",
        "geocoding_address": "Sudur Paschim Vipassana Center, Nepal",
        "latitude": "28.96399",
        "longitude": "80.17715",
        "center": "https://www.dhamma.org/en/schedules/schyana"
    },
    {
        "s_no": "18.0",
        "center_name": "Lukla vipassana center",
        "center_dhamma_name": "Dhamma sagar",
        "address": "Khumbu Pasang Lhamu Rural Municipality-2\nSolukhumbu(Lukla)",
        "established_date": "2021",
        "contact_person": "",
        "dhamma_hall_capacity_male": "35.0",
        "dhamma_hall_capacity_female": "35.0",
        "residence_capacity_male": "12.0",
        "residence_capacity_female": "8.0",
        "at_residence_male": "Y",
        "at_residence_female": "",
        "pagoda": "",
        "remarks": "",
        "extracted_city": "",
        "geocoding_address": "Lukla vipassana center, Nepal",
        "latitude": "27.686899",
        "longitude": "86.729698",
        "center": "https://www.dhamma.org/en/schedules/schsagar"
    }
];
